export const ADD_BLOG = "ADD_BLOG"
export const REMOVE_BLOG = "REMOVE_BLOG"
export const LIKE_BLOGP = "LIKE_BLOGP"
export const LIKE_BLOGM = "LIKE_BLOGM"
export const PUBLISH_BLOG = "PUBLISH_BLOG"
export const SORT_NEWEST = "SORT_NEWEST"
export const SORT_HOTTEST = "SORT_HOTTEST"
export const SORT_OLDEST = "SORT_OLDEST"